/* eslint-disable */
/** Auto-generated by scripts/generate-layouts.mjs — do not edit manually. */
import type { ObjectLayout } from "./layouts";

export const LAYOUTS_BY_SLUG: Record<string, ObjectLayout[]> = {
  "bekturova-348": [
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20348/35%20%D0%BA%D0%B2.webp",
      "area": 35,
      "kind": "apartment",
      "label": "35 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20348/35%20%D0%BA%D0%BA%D0%B2.webp",
      "area": 35,
      "kind": "apartment",
      "label": "35 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20348/37%20%D0%BA%D0%B2.webp",
      "area": 37,
      "kind": "apartment",
      "label": "37 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20348/37%20%D0%BA%D0%BA%D0%B2.webp",
      "area": 37,
      "kind": "apartment",
      "label": "37 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20348/41%20%D0%BA%D0%B2.webp",
      "area": 41,
      "kind": "apartment",
      "label": "41 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20348/44%20%D0%BA%D0%B2.webp",
      "area": 44,
      "kind": "apartment",
      "label": "44 м² · квартира"
    }
  ],
  "bekturova-356": [
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/38%20%D0%BA%D0%B2.webp",
      "area": 38,
      "kind": "apartment",
      "label": "38 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/38%20%D0%BA%D0%BA%D0%B2.webp",
      "area": 38,
      "kind": "apartment",
      "label": "38 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/47%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 47,
      "kind": "apartment",
      "label": "47 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/47%20%D0%BA%D0%BA%D0%B2.webp",
      "area": 47,
      "kind": "apartment",
      "label": "47 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/48%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 48,
      "kind": "apartment",
      "label": "48 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/48%20%D0%BA%D0%B2%D0%BA.webp",
      "area": 48,
      "kind": "apartment",
      "label": "48 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/48%D0%BA%D0%B2.webp",
      "area": 48,
      "kind": "apartment",
      "label": "48 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/50%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 50,
      "kind": "apartment",
      "label": "50 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/50%20%D0%BA%D0%B2%D0%B2%D0%B2.webp",
      "area": 50,
      "kind": "apartment",
      "label": "50 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/50%D0%BA%D0%B2.webp",
      "area": 50,
      "kind": "apartment",
      "label": "50 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/60%20%D0%BA%D0%B2.webp",
      "area": 60,
      "kind": "apartment",
      "label": "60 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/60.webp",
      "area": 60,
      "kind": "apartment",
      "label": "60 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/68%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 68,
      "kind": "apartment",
      "label": "68 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/68%20%D0%BA%D0%BA%D0%B2.webp",
      "area": 68,
      "kind": "apartment",
      "label": "68 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/68%D0%BA%D0%B2.webp",
      "area": 68,
      "kind": "apartment",
      "label": "68 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/69%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 69,
      "kind": "apartment",
      "label": "69 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/69.webp",
      "area": 69,
      "kind": "apartment",
      "label": "69 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/70%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 70,
      "kind": "apartment",
      "label": "70 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/70%20%D0%BA%D0%B2%D0%BA%D0%B2.webp",
      "area": 70,
      "kind": "apartment",
      "label": "70 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/70%D0%BA%D0%B2.webp",
      "area": 70,
      "kind": "apartment",
      "label": "70 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/79%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 79,
      "kind": "apartment",
      "label": "79 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/79%20%D0%BA%D0%BA%D0%BA%D0%B2.webp",
      "area": 79,
      "kind": "apartment",
      "label": "79 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/79%D0%BA%D0%B2.webp",
      "area": 79,
      "kind": "apartment",
      "label": "79 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/88%20%D0%BA%D0%B2.webp",
      "area": 88,
      "kind": "apartment",
      "label": "88 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%91%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%BE%D0%B2%D0%B0%20356/88.webp",
      "area": 88,
      "kind": "apartment",
      "label": "88 м² · квартира"
    }
  ],
  "estaya-90": [
    {
      "src": "/Планировки/%D0%95%D1%81%D1%82%D0%B0%D1%8F%2090/65%20%D0%BA%D0%B2.webp",
      "area": 65,
      "kind": "apartment",
      "label": "65 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%95%D1%81%D1%82%D0%B0%D1%8F%2090/66%20%D0%BA%D0%B2.webp",
      "area": 66,
      "kind": "apartment",
      "label": "66 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%95%D1%81%D1%82%D0%B0%D1%8F%2090/82%20%D0%BA%D0%B2.webp",
      "area": 82,
      "kind": "apartment",
      "label": "82 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%95%D1%81%D1%82%D0%B0%D1%8F%2090/84%20%D0%BA%D0%B2.webp",
      "area": 84,
      "kind": "apartment",
      "label": "84 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%95%D1%81%D1%82%D0%B0%D1%8F%2090/84%20%D0%BA%D0%B2%D0%B2.webp",
      "area": 84,
      "kind": "apartment",
      "label": "84 м² · квартира"
    },
    {
      "src": "/Планировки/%D0%95%D1%81%D1%82%D0%B0%D1%8F%2090/84.webp",
      "area": 84,
      "kind": "apartment",
      "label": "84 м² · квартира"
    }
  ]
} as const;
