import fs from "fs";
import path from "path";

const ROOT = path.join(import.meta.dirname, "..");
const LAYOUTS_DIR = path.join(ROOT, "public/Планировки");

/** Папка в public/Планировки → slug объекта */
const FOLDER_TO_SLUG = {
  "Дюсенова 304": "dyusenova-304",
  "Дюсенова 306": "dyusenova-306",
  "Горького 46": "gorkogo-46",
  "Горького": "gorkogo-46",
  "Естая 90": "estaya-90",
  "Бектурова 348": "bekturova-348",
  "Бектурова 356": "bekturova-356",
};

function parseLayoutMeta(filename) {
  const base = filename.replace(/\.png$/i, "").trim();
  const match = base.match(/^(\d+)\s*(.*)?$/i) ?? base.match(/^(\d+)(.+)?$/i);
  const area = match ? Number(match[1]) : 0;
  const suffix = (match?.[2] ?? "").toLowerCase().replace(/\s/g, "");

  const isCommercial =
    suffix.includes("кк") ||
    /кв{2,}/.test(suffix) ||
    suffix.includes("квк");

  const kind = isCommercial ? "commercial" : "apartment";
  const kindLabel = kind === "commercial" ? "коммерция" : "квартира";

  let label = `${area} м² · ${kindLabel}`;
  if (suffix && suffix !== "кв" && !/^к{2,}в+$/.test(suffix)) {
    label = `${area} м² · ${kindLabel} (${suffix})`;
  }

  return { area, kind, label };
}

function layoutSrc(folder, filename) {
  return `/Планировки/${encodeURIComponent(folder)}/${encodeURIComponent(filename)}`;
}

const bySlug = {};

for (const folder of fs.readdirSync(LAYOUTS_DIR, { withFileTypes: true })) {
  if (!folder.isDirectory()) continue;
  const slug = FOLDER_TO_SLUG[folder.name];
  if (!slug) continue;

  const dir = path.join(LAYOUTS_DIR, folder.name);
  const files = fs
    .readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith(".png"))
    .sort((a, b) => {
      const ma = parseLayoutMeta(a);
      const mb = parseLayoutMeta(b);
      if (ma.area !== mb.area) return ma.area - mb.area;
      if (ma.kind !== mb.kind) return ma.kind === "apartment" ? -1 : 1;
      return a.localeCompare(b, "ru");
    });

  bySlug[slug] = files.map((filename) => {
    const meta = parseLayoutMeta(filename);
    return {
      src: layoutSrc(folder, filename),
      ...meta,
    };
  });
}

const out = `/* eslint-disable */
/** Auto-generated by scripts/generate-layouts.mjs — do not edit manually. */
import type { ObjectLayout } from "./layouts";

export const LAYOUTS_BY_SLUG: Record<string, ObjectLayout[]> = ${JSON.stringify(bySlug, null, 2)} as const;
`;

fs.writeFileSync(path.join(ROOT, "lib/layouts.generated.ts"), out);
console.log(
  Object.entries(bySlug)
    .map(([slug, items]) => `${slug}: ${items.length}`)
    .join(", "),
);
